import browser_cookie3
import os

# Extract Instagram cookies from Chrome/Kiwi browser
try:
    cj = browser_cookie3.chrome(domain_name='.instagram.com')
    
    with open('cookies.txt', 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by update_cookies.py\n\n")
        
        for cookie in cj:
            if 'instagram' in cookie.domain:
                expires = int(cookie.expires) if cookie.expires else 0
                secure = "TRUE" if cookie.secure else "FALSE"
                f.write(f"{cookie.domain}\tTRUE\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n")
    
    print("✅ Cookies updated successfully!")
    print(f"Found {sum(1 for _ in cj)} Instagram cookies")
    
except Exception as e:
    print(f"❌ Error: {e}")
    print("Make sure you're logged into Instagram in Chrome/Kiwi browser")
